apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: dynatrace-otel-collector-gateway
  name: dynatrace-otel-collector-gateway-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-otel-collector-gateway-collector
  labels:
    app: dynatrace-otel-collector-gateway
rules:
  - apiGroups:
      - ''
    resources:
      - 'pods'
      - 'namespaces'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
  - apiGroups:
      - 'apps'
    resources:
      - 'replicasets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'extensions'
    resources:
      - 'replicasets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-otel-collector-gateway
  labels:
    app: dynatrace-otel-collector-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-otel-collector-gateway-collector
subjects:
  - kind: ServiceAccount
    name: dynatrace-otel-collector-gateway-collector
    namespace: astroshop
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: dynatrace-otel-collector-gateway
spec:
  serviceAccount: dynatrace-otel-collector-gateway-collector
  envFrom:
  - secretRef:
      name: dynatrace-otelcol-dt-api-credentials
  env:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: CLUSTER_NAME
    value: "aeric-walls-gke"
  mode: "deployment"
  image: "ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:0.46.0"
  resources:
    limits:
      memory: 512Mi
  config:
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            cors:
              allowed_origins:
              - http://*
              - https://*
            endpoint: ${env:MY_POD_IP}:4318

    processors:
      cumulativetodelta:
        max_staleness: 25h
      transform:
        error_mode: ignore
        trace_statements: &dynatrace_transformations
          # Set attributes taken from k8s metadata.
          - context: resource
            statements:
              - set(attributes["k8s.cluster.name"], "${env:CLUSTER_NAME}")
              - set(attributes["k8s.workload.kind"], "job") where IsString(attributes["k8s.job.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.job.name"]) where IsString(attributes["k8s.job.name"])
              - set(attributes["k8s.workload.kind"], "cronjob") where IsString(attributes["k8s.cronjob.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.cronjob.name"]) where IsString(attributes["k8s.cronjob.name"])
              - set(attributes["k8s.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["k8s.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["k8s.workload.kind"], "replicaset") where IsString(attributes["k8s.replicaset.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.replicaset.name"]) where IsString(attributes["k8s.replicaset.name"])
              - set(attributes["k8s.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              # remove the delete statements if you want to preserve these attributes
              - delete_key(attributes, "k8s.deployment.name")
              - delete_key(attributes, "k8s.replicaset.name")
              - delete_key(attributes, "k8s.statefulset.name")
              - delete_key(attributes, "k8s.daemonset.name")
              - delete_key(attributes, "k8s.cronjob.name")
              - delete_key(attributes, "k8s.job.name")
          # Set attributes from metadata specified in Dynatrace and set through the Dynatrace Operator.
          # For more info: https://docs.dynatrace.com/docs/shortlink/k8s-metadata-telemetry-enrichment
          - context: resource
            statements:
              - merge_maps(attributes, ParseJSON(attributes["metadata.dynatrace.com"]), "upsert") where IsMatch(attributes["metadata.dynatrace.com"], "^\\{")
              - delete_key(attributes, "metadata.dynatrace.com")
        metric_statements: *dynatrace_transformations
        log_statements: *dynatrace_transformations
      k8sattributes:
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.pod.ip
            - k8s.deployment.name
            - k8s.replicaset.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.job.name
            - k8s.cronjob.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.cluster.uid
            - k8s.container.name
          annotations:
            - from: pod
              key_regex: metadata.dynatrace.com/(.*)
              tag_name: $$1
            - from: pod
              key: metadata.dynatrace.com
              tag_name: metadata.dynatrace.com
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

    exporters:
      otlp_http:
        endpoint: ${env:DT_ENDPOINT}
        headers:
          Authorization: "Api-Token ${env:DT_API_TOKEN}"

    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes, transform]
          exporters: [otlp_http]
        metrics:
          receivers: [otlp]
          processors: [k8sattributes, transform, cumulativetodelta]
          exporters: [otlp_http]
        logs:
          receivers: [otlp]
          processors: [k8sattributes, transform]
          exporters: [otlp_http]
      telemetry:
        metrics:
          # metrics verbosity level. Higher verbosity means more metrics.
          # The dashboard relies on metrics at level detailed.
          level: detailed
          # set up OTLP exporter
          readers:
            - periodic:
                interval: 60000
                exporter:
                  otlp:
                    protocol: http/protobuf
                    temporality_preference: delta
                    endpoint: "${env:DT_ENDPOINT}/v1/metrics"
                    headers:
                      - name: Authorization
                        value: "Api-Token ${env:DT_API_TOKEN}"