# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Build images on Kubernetes runners

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version used when tagging the image
        default: 'dev'
        required: false
        type: string
      dockerhub_repo:
        description: Docker Hub repository
        default: 'otel/demo'
        required: false
        type: string

permissions:
  contents: read

jobs:
  build_and_push_images:
    runs-on: otel-demo-builders
    strategy:
      fail-fast: false
      matrix:
        file_tag:
          - file: ./src/accounting/Dockerfile
            tag_suffix: accounting
            context: ./
          - file: ./src/ad/Dockerfile
            tag_suffix: ad
            context: ./
          - file: ./src/cart/src/Dockerfile
            tag_suffix: cart
            context: ./
          - file: ./src/checkout/Dockerfile
            tag_suffix: checkout
            context: ./
          - file: ./src/currency/Dockerfile
            tag_suffix: currency
            context: ./
          - file: ./src/email/Dockerfile
            tag_suffix: email
            context: ./
          - file: ./src/flagd-ui/Dockerfile
            tag_suffix: flagd-ui
            context: ./
          - file: ./src/fraud-detection/Dockerfile
            tag_suffix: fraud-detection
            context: ./
          - file: ./src/frontend/Dockerfile
            tag_suffix: frontend
            context: ./
          - file: ./src/frontend-proxy/Dockerfile
            tag_suffix: frontend-proxy
            context: ./
          - file: ./src/frontend/Dockerfile.cypress
            tag_suffix: frontend-tests
            context: ./
          - file: ./src/image-provider/Dockerfile
            tag_suffix: image-provider
            context: ./
          - file: ./src/kafka/Dockerfile
            tag_suffix: kafka
            context: ./
          - file: ./src/llm/Dockerfile
            tag_suffix: llm
            context: ./
          - file: ./src/load-generator/Dockerfile
            tag_suffix: load-generator
            context: ./
          - file: ./src/opensearch/Dockerfile
            tag_suffix: opensearch
            context: ./
          - file: ./src/payment/Dockerfile
            tag_suffix: payment
            context: ./
          - file: ./src/product-catalog/Dockerfile
            tag_suffix: product-catalog
            context: ./
          - file: ./src/product-reviews/Dockerfile
            tag_suffix: product-reviews
            context: ./
          - file: ./src/quote/Dockerfile
            tag_suffix: quote
            context: ./
          - file: ./src/recommendation/Dockerfile
            tag_suffix: recommendation
            context: ./
          - file: ./src/shipping/Dockerfile
            tag_suffix: shipping
            context: ./
          - file: ./src/telemetry-docs/Dockerfile
            tag_suffix: telemetry-docs
            context: ./
          - file: ./test/tracetesting/Dockerfile
            tag_suffix: traceBasedTests
            context: ./

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
      - name: Load environment variables from .env file
        run: |
          if [ -f .env ]; then
            grep -vE '^\s*#|^\s*$' .env | while read -r line; do
              echo "$line" >> $GITHUB_ENV
            done
          else
            echo ".env file not found!"
            exit 1
          fi
      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121  # v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a  # v4.0.0
        with:
          image: tonistiigi/binfmt:master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd  # v4.0.0
        with:
          buildkitd-config-inline: |
            [worker.oci]
            max-parallelism = 2
      - name: Build and push demo image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f  # v7.1.0
        with:
          context: ${{ matrix.file_tag.context }}
          file: ${{ matrix.file_tag.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            OTEL_JAVA_AGENT_VERSION=${{ env.OTEL_JAVA_AGENT_VERSION }}
            OPENTELEMETRY_CPP_VERSION=${{ env.OPENTELEMETRY_CPP_VERSION }}
            TRACETEST_IMAGE_VERSION=${{ env.TRACETEST_IMAGE_VERSION }}
            OPENSEARCH_IMAGE=${{ env.OPENSEARCH_IMAGE }}
          tags: |
            ${{ inputs.dockerhub_repo }}:${{ inputs.version }}-${{ matrix.file_tag.tag_suffix }}
            ${{ inputs.dockerhub_repo }}:latest-${{ matrix.file_tag.tag_suffix }}
          cache-from: type=gha
          cache-to: type=gha
